### PR TITLE
blankline after multiline expression

### PR DESCRIPTION
**Pull request by kuceb**
examples of what this fixes:

image

image

image

### CODE REVIEW

**Comment by chrisbreiding** [comment]
Can you post an example of what this does?

Does it mean the following:

```javascript
const foo = {
  bar: 'baz',
}
const bar = 'baz'
```

will have to be the following?

```javascript
const foo = {
  bar: 'baz',
}

const bar = 'baz'
```

**Comment by kuceb** [comment]
no, it means:

```js
sinon
.stub(fs, 'pathExistsAsync')
.withArgs(binaryPkgPath)
.resolves(true)
sinon
.stub(fs, 'readJsonAsync')
.withArgs(binaryPkgPath)
.resolves({ version: '2.0.48' })
```
will have to be 
```js
sinon
.stub(fs, 'pathExistsAsync')
.withArgs(binaryPkgPath)
.resolves(true)

sinon
.stub(fs, 'readJsonAsync')
.withArgs(binaryPkgPath)
.resolves({ version: '2.0.48' })
```

**Comment by kuceb** [comment]
also will add newlines between it/describe blocks
```js
it('foo', () => {
})

it('bar', () => {
})
```

**Comment by brian-mann** [comment]
Ohhh this is perfect. Exactly what we were looking for.

**Pull request merged**
